spring:
  config:
    activate:
      on-profile: "qa"
build:
  version: "2.0"

loan:
  message: Welcome to Lazy Bank QA - Loan Department"
  contactDetails:
    name: "Sunit Patel - QA"
    email: "spatel@lazybank.co.in"
    phone: "+91-8787675432"
  onCallSupport:
    - (555) 123-4567
    - (555) 987-6543